# Generated by Django 5.2.3 on 2025-09-27 23:40

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('document', 'Documento'), ('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Otro')], default='document', max_length=20)),
                ('file', models.FileField(help_text='Archivo organizado por fecha', upload_to='uploads/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Miniatura opcional', null=True, upload_to='thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Archivo de Demostración',
                'verbose_name_plural': 'Archivos de Demostración',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen para la galería', upload_to='gallery/')),
                ('caption', models.CharField(blank=True, help_text='Descripción opcional de la imagen', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documentos.gallery')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Archivo del usuario (se organizará por carpetas)', upload_to=documentos.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload de Usuario',
                'verbose_name_plural': 'Uploads de Usuarios',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
